#!/bin/bash

# Define the .env file path
BACKEND_ENV_FILE_PATH="app/backend/.env"
FRONTEND_ENV_FILE_PATH="app/frontend/.env"

# Clear the contents of the .env file#!/bin/bash

# Define the .env file paths
BACKEND_ENV_FILE_PATH="app/backend/.env"
FRONTEND_ENV_FILE_PATH="app/frontend/.env"

# Clear the contents of the .env files
> $BACKEND_ENV_FILE_PATH
> $FRONTEND_ENV_FILE_PATH

# Append new values to the backend .env file
echo "AZURE_OPENAI_ENDPOINT=$(azd env get-valuep AZURE_OPENAI_ENDPOINT)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_OPENAI_REALTIME_DEPLOYMENT=$(azd env get-value AZURE_OPENAI_REALTIME_DEPLOYMENT)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_OPENAI_REALTIME_VOICE_CHOICE=$(azd env get-value AZURE_OPENAI_REALTIME_VOICE_CHOICE)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_OPENAI_REALTIME_VOICE_NAME=$(azd env get-value AZURE_OPENAI_REALTIME_VOICE_NAME)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_OPENAI_REALTIME_VOICE_MODEL_VERSION=$(azd env get-value AZURE_OPENAI_REALTIME_VOICE_MODEL_VERSION)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_ENDPOINT=$(azd env get-value AZURE_SEARCH_ENDPOINT)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_INDEX=$(azd env get-value AZURE_SEARCH_INDEX)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_TENANT_ID=$(azd env get-value AZURE_TENANT_ID)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_SEMANTIC_CONFIGURATION=$(azd env get-value AZURE_SEARCH_SEMANTIC_CONFIGURATION)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_IDENTIFIER_FIELD=$(azd env get-value AZURE_SEARCH_IDENTIFIER_FIELD)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_CONTENT_FIELD=$(azd env get-value AZURE_SEARCH_CONTENT_FIELD)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_TITLE_FIELD=$(azd env get-value AZURE_SEARCH_TITLE_FIELD)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_EMBEDDING_FIELD=$(azd env get-value AZURE_SEARCH_EMBEDDING_FIELD)" >> $BACKEND_ENV_FILE_PATH
echo "AZURE_SEARCH_USE_VECTOR_QUERY=$(azd env get-value AZURE_SEARCH_USE_VECTOR_QUERY)" >> $BACKEND_ENV_FILE_PATH

# Append new values to the frontend .env file
echo "VITE_AZURE_API_ENDPOINT=$(azd env get-value AZURE_API_ENDPOINT)" >> $FRONTEND_ENV_FILE_PATH
> $BACKEND_ENV_FILE_PATH
> $FRONTEND_ENV_FILE_PATH
